var express = require('express');
var router = express.Router();
var sequelize = require('../models/db');
//below autogenerated routes
router.get('/', function (req, res) {
  sequelize.models.TelevisoresListados.findAll().then(recordsFromTelevisoresListados => {
   sequelize.models.COmentario.findAll().then(recordsFromCOmentario => {
   res.render('rendered/index', { title: 'Index',   recordsFromTelevisoresListados : recordsFromTelevisoresListados,   recordsFromCOmentario : recordsFromCOmentario });
  });
  });
});

router.get('/page', function(req, res) {
  res.render('rendered/page', { title: 'Page' });
});

router.post("/insertOneInTelevisoresListados", function(req, res){
  sequelize.models.TelevisoresListados.create({
    titulo: req.body.titulo,
    precio: req.body.precio
  })
  .then(()=> {res.redirect('back')})
  .catch(error => {console.log(error);res.redirect('back')});
});

router.get("/updateOneInTelevisoresListados/:id", function(req, res){
  sequelize.models.TelevisoresListados.findById(req.params.id).then(record => {
    res.render("rendered/formUpdateOneInTelevisoresListados", { title: "Update in TelevisoresListados", record : record })
  });
});

router.post("/updateOneInTelevisoresListados", function(req, res){
  sequelize.models.TelevisoresListados.findById(req.body.id).then(record => {
    record.titulo = req.body.titulo;
    record.precio = req.body.precio;
    record.save()
    .then(()=> {res.render("rendered/formUpdateOneInTelevisoresListados", { title: "Update in TelevisoresListados", record : record })})
    .catch(error => {console.log(error);res.redirect('back')});
  });
});

router.get("/deleteOneFromTelevisoresListados/:id", function(req, res){
  sequelize.models.TelevisoresListados.findById(req.params.id).then(record => {
    record.destroy().then(()=> {res.redirect('back')})
  });
});

router.get("/detailOfOneFromTelevisoresListados/:id", function(req, res){
  sequelize.models.TelevisoresListados.findById(req.params.id).then(record => {
    res.render("rendered/detailFromTelevisoresListados", { title: "Detail of record from TelevisoresListados", record : record });
  });
});

router.post("/insertOneInCOmentario", function(req, res){
  sequelize.models.COmentario.create({
    TextoComentario: req.body.TextoComentario
  })
  .then(()=> {res.redirect('back')})
  .catch(error => {console.log(error);res.redirect('back')});
});

router.get("/updateOneInCOmentario/:id", function(req, res){
  sequelize.models.COmentario.findById(req.params.id).then(record => {
    res.render("rendered/formUpdateOneInCOmentario", { title: "Update in COmentario", record : record })
  });
});

router.post("/updateOneInCOmentario", function(req, res){
  sequelize.models.COmentario.findById(req.body.id).then(record => {
    record.TextoComentario = req.body.TextoComentario;
    record.save()
    .then(()=> {res.render("rendered/formUpdateOneInCOmentario", { title: "Update in COmentario", record : record })})
    .catch(error => {console.log(error);res.redirect('back')});
  });
});

router.get("/deleteOneFromCOmentario/:id", function(req, res){
  sequelize.models.COmentario.findById(req.params.id).then(record => {
    record.destroy().then(()=> {res.redirect('back')})
  });
});

router.get("/detailOfOneFromCOmentario/:id", function(req, res){
  sequelize.models.COmentario.findById(req.params.id).then(record => {
    res.render("rendered/detailFromCOmentario", { title: "Detail of record from COmentario", record : record });
  });
});


module.exports = router;
