var express = require('express');
var router = express.Router();
var sequelize = require('../models/db');
//below autogenerated routes
router.get('/', function (req, res) {
  sequelize.models.Comentarios.findAll({
    where: {
      TelevisoresListadoId: 1
    }
  }).then(recordsFromComentarios => {
   res.render('rendered/index', { title: 'Index',   recordsFromComentarios : recordsFromComentarios });
  });
});

router.post("/insertOneInTelevisoresListado", function(req, res){
  sequelize.models.TelevisoresListado.create({
    precio: req.body.precio,
    titulo: req.body.titulo
  })
  .then(()=> {res.redirect('back')})
  .catch(error => {console.log(error);res.redirect('back')});
});

router.get("/updateOneInTelevisoresListado/:id", function(req, res){
  sequelize.models.TelevisoresListado.findById(req.params.id).then(record => {
    res.render("rendered/formUpdateOneInTelevisoresListado", { title: "Update in TelevisoresListado", record : record })
  });
});

router.post("/updateOneInTelevisoresListado", function(req, res){
  sequelize.models.TelevisoresListado.findById(req.body.id).then(record => {
    record.precio = req.body.precio;
    record.titulo = req.body.titulo;
    record.save()
    .then(()=> {res.render("rendered/formUpdateOneInTelevisoresListado", { title: "Update in TelevisoresListado", record : record })})
    .catch(error => {console.log(error);res.redirect('back')});
  });
});

router.get("/deleteOneFromTelevisoresListado/:id", function(req, res){
  sequelize.models.TelevisoresListado.findById(req.params.id).then(record => {
    record.destroy().then(()=> {res.redirect('back')})
  });
});

router.get("/detailOfOneFromTelevisoresListado/:id", function(req, res){
  sequelize.models.TelevisoresListado.findById(req.params.id).then(record => {
    res.render("rendered/detailFromTelevisoresListado", { title: "Detail of record from TelevisoresListado", record : record });
  });
});

router.post("/insertOneInComentarios", function(req, res){
  sequelize.models.Comentarios.create({
    property: req.body.property
  })
  .then(()=> {res.redirect('back')})
  .catch(error => {console.log(error);res.redirect('back')});
});

router.get("/updateOneInComentarios/:id", function(req, res){
  sequelize.models.Comentarios.findById(req.params.id).then(record => {
    res.render("rendered/formUpdateOneInComentarios", { title: "Update in Comentarios", record : record })
  });
});

router.post("/updateOneInComentarios", function(req, res){
  sequelize.models.Comentarios.findById(req.body.id).then(record => {
    record.property = req.body.property;
    record.save()
    .then(()=> {res.render("rendered/formUpdateOneInComentarios", { title: "Update in Comentarios", record : record })})
    .catch(error => {console.log(error);res.redirect('back')});
  });
});

router.get("/deleteOneFromComentarios/:id", function(req, res){
  sequelize.models.Comentarios.findById(req.params.id).then(record => {
    record.destroy().then(()=> {res.redirect('back')})
  });
});

router.get("/detailOfOneFromComentarios/:id", function(req, res){
  sequelize.models.Comentarios.findById(req.params.id).then(record => {
    res.render("rendered/detailFromComentarios", { title: "Detail of record from Comentarios", record : record });
  });
});


module.exports = router;
