var express = require('express');
var router = express.Router();
var sequelize = require('../models/db');
//below autogenerated routes
router.get('/', function (req, res) {
  sequelize.models.Descripciones.findAll().then(recordsFromDescripciones => {
   res.render('rendered/index', { title: 'Index',   recordsFromDescripciones : recordsFromDescripciones });
  });
});

router.post("/insertOneInDescripciones", function(req, res){
  sequelize.models.Descripciones.create({
    estrellas: req.body.estrellas
  })
  .then(()=> {res.redirect('back')})
  .catch(error => {console.log(error);res.redirect('back')});
});

router.get("/updateOneInDescripciones/:id", function(req, res){
  sequelize.models.Descripciones.findById(req.params.id).then(record => {
    res.render("rendered/formUpdateOneInDescripciones", { title: "Update in Descripciones", record : record })
  });
});

router.post("/updateOneInDescripciones", function(req, res){
  sequelize.models.Descripciones.findById(req.body.id).then(record => {
    record.estrellas = req.body.estrellas;
    record.save()
    .then(()=> {res.render("rendered/formUpdateOneInDescripciones", { title: "Update in Descripciones", record : record })})
    .catch(error => {console.log(error);res.redirect('back')});
  });
});

router.get("/deleteOneFromDescripciones/:id", function(req, res){
  sequelize.models.Descripciones.findById(req.params.id).then(record => {
    record.destroy().then(()=> {res.redirect('back')})
  });
});

router.get("/detailOfOneFromDescripciones/:id", function(req, res){
  sequelize.models.Descripciones.findById(req.params.id).then(record => {
    res.render("rendered/detailFromDescripciones", { title: "Detail of record from Descripciones", record : record });
  });
});


module.exports = router;
